# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/qt_ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("source/qt_ui/../maze.ico"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap("source/qt_ui/../maze.ico"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.On,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.pool = QtWidgets.QWidget(MainWindow)
        self.pool.setObjectName("pool")
        MainWindow.setCentralWidget(self.pool)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuLanguage_selection = QtWidgets.QMenu(self.menuSettings)
        icon = QtGui.QIcon.fromTheme("ru")
        self.menuLanguage_selection.setIcon(icon)
        self.menuLanguage_selection.setObjectName("menuLanguage_selection")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCreateMap = QtWidgets.QAction(MainWindow)
        self.actionCreateMap.setObjectName("actionCreateMap")
        self.actionRandomMap = QtWidgets.QAction(MainWindow)
        self.actionRandomMap.setObjectName("actionRandomMap")
        self.actionFillMap = QtWidgets.QAction(MainWindow)
        self.actionFillMap.setObjectName("actionFillMap")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-contents")
        self.actionTutorial.setIcon(icon)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("emblem-system")
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRu = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("source/qt_ui/../ru.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionRu.setIcon(icon1)
        self.actionRu.setObjectName("actionRu")
        self.actionEn = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("source/qt_ui/../en.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionEn.setIcon(icon2)
        self.actionEn.setObjectName("actionEn")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-in")
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.actionZoomOut.setIcon(icon)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionExportAdjacencyMap = QtWidgets.QAction(MainWindow)
        self.actionExportAdjacencyMap.setObjectName("actionExportAdjacencyMap")
        self.actionExportXmlMaze = QtWidgets.QAction(MainWindow)
        self.actionExportXmlMaze.setObjectName("actionExportXmlMaze")
        self.actionExportXmlLineMap = QtWidgets.QAction(MainWindow)
        self.actionExportXmlLineMap.setObjectName("actionExportXmlLineMap")
        self.actionAboutApplication = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAboutApplication.setIcon(icon)
        self.actionAboutApplication.setObjectName("actionAboutApplication")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuTools.addAction(self.actionCreateMap)
        self.menuTools.addAction(self.actionRandomMap)
        self.menuTools.addAction(self.actionFillMap)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionAboutApplication)
        self.menuLanguage_selection.addAction(self.actionRu)
        self.menuLanguage_selection.addAction(self.actionEn)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addAction(self.menuLanguage_selection.menuAction())
        self.menuFile.addAction(self.actionExportAdjacencyMap)
        self.menuFile.addAction(self.actionExportXmlMaze)
        self.menuFile.addAction(self.actionExportXmlLineMap)
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "maze-gui-generator"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuLanguage_selection.setTitle(
            _translate("MainWindow", "Language selection/ Выбор языка")
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionCreateMap.setText(_translate("MainWindow", "Create a map"))
        self.actionCreateMap.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRandomMap.setText(_translate("MainWindow", "Random this map"))
        self.actionRandomMap.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionFillMap.setText(_translate("MainWindow", "Fill this map"))
        self.actionFillMap.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionTutorial.setText(_translate("MainWindow", "Small help"))
        self.actionTutorial.setShortcut(_translate("MainWindow", "F1"))
        self.actionSettings.setText(_translate("MainWindow", "Preferences"))
        self.actionSettings.setToolTip(_translate("MainWindow", "Preferences"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionRu.setText(_translate("MainWindow", "ru"))
        self.actionEn.setText(_translate("MainWindow", "en"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoomIn.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom out"))
        self.actionZoomOut.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionExportAdjacencyMap.setText(
            _translate("MainWindow", "Export adjacency map (.txt)")
        )
        self.actionExportXmlMaze.setText(
            _translate("MainWindow", "Export maze field (.xml)")
        )
        self.actionExportXmlLineMap.setText(
            _translate("MainWindow", "Export maze field with lines (.xml)")
        )
        self.actionAboutApplication.setText(
            _translate("MainWindow", "About maze-gui-generator")
        )
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
