# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWidget(object):
    def setupUi(self, aboutWidget):
        aboutWidget.setObjectName("aboutWidget")
        aboutWidget.resize(429, 257)
        aboutWidget.setMinimumSize(QtCore.QSize(429, 257))
        aboutWidget.setMaximumSize(QtCore.QSize(429, 257))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../maze.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        aboutWidget.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(aboutWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 441, 251))
        self.label.setMinimumSize(QtCore.QSize(441, 251))
        self.label.setMaximumSize(QtCore.QSize(441, 251))
        self.label.setObjectName("label")

        self.retranslateUi(aboutWidget)
        QtCore.QMetaObject.connectSlotsByName(aboutWidget)

    def retranslateUi(self, aboutWidget):
        _translate = QtCore.QCoreApplication.translate
        aboutWidget.setWindowTitle(_translate("aboutWidget", "About maze-gui-generator"))
        self.label.setText(_translate("aboutWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Program: maze-gui-gen</span></p><p align=\"center\"><span style=\" font-size:14pt;\">GUI field generator for Trik Studio simulator.</span></p><p align=\"center\"><span style=\" font-size:14pt;\"><br/></span></p><p align=\"center\"><span style=\" font-size:14pt;\">Version: 1.2</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Author: Kozlov Lev</span></p></body></html>"))
