# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationWidget(object):
    def setupUi(self, InformationWidget):
        InformationWidget.setObjectName("InformationWidget")
        InformationWidget.resize(400, 298)

        self.retranslateUi(InformationWidget)
        QtCore.QMetaObject.connectSlotsByName(InformationWidget)

    def retranslateUi(self, InformationWidget):
        _translate = QtCore.QCoreApplication.translate
        InformationWidget.setWindowTitle(_translate("InformationWidget", "Form"))
