# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/maze.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.pool = QtWidgets.QWidget(MainWindow)
        self.pool.setObjectName("pool")
        MainWindow.setCentralWidget(self.pool)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menuBar.setObjectName("menuBar")
        self.menutools = QtWidgets.QMenu(self.menuBar)
        self.menutools.setObjectName("menutools")
        self.menulan = QtWidgets.QMenu(self.menuBar)
        self.menulan.setObjectName("menulan")
        MainWindow.setMenuBar(self.menuBar)
        self.actioncreate_map = QtWidgets.QAction(MainWindow)
        self.actioncreate_map.setObjectName("actioncreate_map")
        self.actionexport_xml_maze = QtWidgets.QAction(MainWindow)
        self.actionexport_xml_maze.setObjectName("actionexport_xml_maze")
        self.actionexport_xml_line_map = QtWidgets.QAction(MainWindow)
        self.actionexport_xml_line_map.setObjectName("actionexport_xml_line_map")
        self.actionexport_adjacency_map = QtWidgets.QAction(MainWindow)
        self.actionexport_adjacency_map.setObjectName("actionexport_adjacency_map")
        self.actionsettings = QtWidgets.QAction(MainWindow)
        self.actionsettings.setObjectName("actionsettings")
        self.actionrandom_this_map = QtWidgets.QAction(MainWindow)
        self.actionrandom_this_map.setObjectName("actionrandom_this_map")
        self.actionfill_this_map = QtWidgets.QAction(MainWindow)
        self.actionfill_this_map.setObjectName("actionfill_this_map")
        self.actioninformation = QtWidgets.QAction(MainWindow)
        self.actioninformation.setObjectName("actioninformation")
        self.actionen = QtWidgets.QAction(MainWindow)
        self.actionen.setObjectName("actionen")
        self.actionru = QtWidgets.QAction(MainWindow)
        self.actionru.setObjectName("actionru")
        self.menutools.addAction(self.actioncreate_map)
        self.menutools.addAction(self.actionrandom_this_map)
        self.menutools.addAction(self.actionfill_this_map)
        self.menutools.addAction(self.actionexport_xml_maze)
        self.menutools.addAction(self.actionexport_xml_line_map)
        self.menutools.addAction(self.actionexport_adjacency_map)
        self.menutools.addSeparator()
        self.menutools.addAction(self.actionsettings)
        self.menutools.addAction(self.actioninformation)
        self.menulan.addAction(self.actionen)
        self.menulan.addAction(self.actionru)
        self.menuBar.addAction(self.menutools.menuAction())
        self.menuBar.addAction(self.menulan.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "maze-map-gui-generator"))
        self.menutools.setTitle(_translate("MainWindow", "Tools"))
        self.menulan.setTitle(_translate("MainWindow", "lan/ язык"))
        self.actioncreate_map.setText(_translate("MainWindow", "create map"))
        self.actionexport_xml_maze.setText(_translate("MainWindow", "export xml maze"))
        self.actionexport_xml_line_map.setText(_translate("MainWindow", "export xml line map"))
        self.actionexport_adjacency_map.setText(_translate("MainWindow", "export adjacency map"))
        self.actionsettings.setText(_translate("MainWindow", "settings"))
        self.actionrandom_this_map.setText(_translate("MainWindow", "random this map"))
        self.actionfill_this_map.setText(_translate("MainWindow", "fill this map"))
        self.actioninformation.setText(_translate("MainWindow", "tutorial"))
        self.actionen.setText(_translate("MainWindow", "en"))
        self.actionru.setText(_translate("MainWindow", "ru"))
