# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsForm(object):
    def setupUi(self, settingsForm):
        settingsForm.setObjectName("settingsForm")
        settingsForm.setWindowModality(QtCore.Qt.NonModal)
        settingsForm.resize(610, 95)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settingsForm.sizePolicy().hasHeightForWidth())
        settingsForm.setSizePolicy(sizePolicy)
        settingsForm.setMinimumSize(QtCore.QSize(610, 95))
        settingsForm.setMaximumSize(QtCore.QSize(610, 95))
        self.horizontalLayout = QtWidgets.QHBoxLayout(settingsForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.colorLabel = QtWidgets.QLabel(settingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorLabel.sizePolicy().hasHeightForWidth())
        self.colorLabel.setSizePolicy(sizePolicy)
        self.colorLabel.setStyleSheet("QLabel {border: 3px solid blue;}")
        self.colorLabel.setText("")
        self.colorLabel.setObjectName("colorLabel")
        self.gridLayout.addWidget(self.colorLabel, 2, 2, 1, 1)
        self.mazeSlider = QtWidgets.QSlider(settingsForm)
        self.mazeSlider.setMinimum(1)
        self.mazeSlider.setMaximum(5)
        self.mazeSlider.setProperty("value", 3)
        self.mazeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mazeSlider.setObjectName("mazeSlider")
        self.gridLayout.addWidget(self.mazeSlider, 1, 1, 1, 2)
        self.lineCellSizeLabel = QtWidgets.QLabel(settingsForm)
        self.lineCellSizeLabel.setObjectName("lineCellSizeLabel")
        self.gridLayout.addWidget(self.lineCellSizeLabel, 0, 0, 1, 1)
        self.mazeCellSizeLabel = QtWidgets.QLabel(settingsForm)
        self.mazeCellSizeLabel.setObjectName("mazeCellSizeLabel")
        self.gridLayout.addWidget(self.mazeCellSizeLabel, 1, 0, 1, 1)
        self.lineColorLabel = QtWidgets.QLabel(settingsForm)
        self.lineColorLabel.setObjectName("lineColorLabel")
        self.gridLayout.addWidget(self.lineColorLabel, 2, 0, 1, 1)
        self.lineColorLineEdit = QtWidgets.QLineEdit(settingsForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineColorLineEdit.sizePolicy().hasHeightForWidth())
        self.lineColorLineEdit.setSizePolicy(sizePolicy)
        self.lineColorLineEdit.setAutoFillBackground(False)
        self.lineColorLineEdit.setStyleSheet("QLabel { background-color: rgba(\"+values+\"); }")
        self.lineColorLineEdit.setObjectName("lineColorLineEdit")
        self.gridLayout.addWidget(self.lineColorLineEdit, 2, 1, 1, 1)
        self.lineSlider = QtWidgets.QSlider(settingsForm)
        self.lineSlider.setStyleSheet("QSlider::groove:vertical {\n"
"    background: red;\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: green;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: pink;\n"
"}")
        self.lineSlider.setMinimum(1)
        self.lineSlider.setMaximum(5)
        self.lineSlider.setProperty("value", 2)
        self.lineSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lineSlider.setObjectName("lineSlider")
        self.gridLayout.addWidget(self.lineSlider, 0, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(settingsForm)
        QtCore.QMetaObject.connectSlotsByName(settingsForm)

    def retranslateUi(self, settingsForm):
        _translate = QtCore.QCoreApplication.translate
        settingsForm.setWindowTitle(_translate("settingsForm", "Settings"))
        self.mazeSlider.setToolTip(_translate("settingsForm", "<html><head/><body><p>Displays length of map cell. Values from 1 to 5, from left to right.</p></body></html>"))
        self.lineCellSizeLabel.setText(_translate("settingsForm", "Line cell size (in Trik Studio cells)"))
        self.mazeCellSizeLabel.setText(_translate("settingsForm", "Maze cell size (in Trik Studio cells)"))
        self.lineColorLabel.setText(_translate("settingsForm", "Line color (in hexidemal #000000)"))
        self.lineColorLineEdit.setText(_translate("settingsForm", "#000000"))
        self.lineSlider.setToolTip(_translate("settingsForm", "<html><head/><body><p>Displays length of map cell. Values from 1 to 5, from left to right.</p></body></html>"))
